// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateUserOperation OperationName = "CreateUser"
	GetUserOperation    OperationName = "GetUser"
	GetUsersOperation   OperationName = "GetUsers"
	PingOperation       OperationName = "Ping"
)
