// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateUser implements createUser operation.
	//
	// Create a user.
	//
	// POST /api/v1/users
	CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUser, error)
	// GetUser implements getUser operation.
	//
	// Get user by ID.
	//
	// GET /api/v1/users/{userID}
	GetUser(ctx context.Context, params GetUserParams) (*User, error)
	// GetUsers implements getUsers operation.
	//
	// Get all users.
	//
	// GET /api/v1/users
	GetUsers(ctx context.Context) ([]User, error)
	// Ping implements ping operation.
	//
	// Ping API.
	//
	// GET /api/v1/ping
	Ping(ctx context.Context) (PingOK, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
